name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: [master]

jobs:
  bof-build:
    name: Build and publish tagged release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip \
          mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib jq

      - name: Minisign
        run: |
          MINISIGN_TMP=`mktemp -d`
          cd $MINISIGN_TMP
          wget https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
          tar xvf minisign-linux-amd64.tar.gz
          mv ./minisign ~/minisign
          touch ~/minisign.key && chmod 600 ~/minisign.key
          echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key
          ls -l ~/
          realpath ~/

      - name: Check out code
        uses: actions/checkout@v2

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Packages Setup
        run: |
          mkdir packages

      - name: ProcessDestroy
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ProcessDestroy

      - name: ProcessListHandles
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ProcessListHandles
          
      - name: adcs_request
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh adcs_request

      - name: adduser
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh adduser

      - name: addusertogroup
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh addusertogroup

      - name: chromeKey
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh chromeKey

      - name: enableuser
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh enableuser

      - name: lastpass
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh lastpass

      - name: office_tokens
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh office_tokens

      - name: procdump
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh procdump

      - name: reg_delete
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh reg_delete

      - name: reg_save
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh reg_save

      - name: reg_set
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh reg_set

      - name: sc_config
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_config

      - name: sc_create
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_create

      - name: sc_delete
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_delete

      - name: sc_description
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_description

      - name: sc_start
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_start

      - name: sc_stop
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_stop

      - name: schtaskscreate
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtaskscreate

      - name: schtasksdelete
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtasksdelete

      - name: schtasksrun
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtasksrun

      - name: schtasksstop
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtasksstop

      - name: setuserpass
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh setuserpass

      - name: shspawnas
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh shspawnas

      - name: suspendresume
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh suspendresume

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./packages/*.tar.gz
            ./packages/*.minisig